version: '3'

services:
  postgresql:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: monitoring_user
      POSTGRES_PASSWORD: IOT123!
    ports:
      - "5432:5432"

  iotmonitor:
    image: iotmonitor:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/monitoring
      SPRING_DATASOURCE_USERNAME: monitoring_user
      SPRING_DATASOURCE_PASSWORD: IOT123!
    ports:
      - "8080:8080"

volumes:
  postgres_data: